# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!(username: "jimmy", password: "test", email: "jimmy@test.com", admin: false)
User.create!(username: "a_guy", password: "test", email: "a_guy@test.com", admin: false)
User.create!(username: "sandy22", password: "test", email: "sandy22@test.com", admin: false)
User.create!(username: "sally", password: "test", email: "sally@test.com", admin: false)
User.create!(username: "jonny", password: "test", email: "jonny@test.com", admin: false)
User.create!(username: "joe", password: "test", email: "joe@test.com", admin: false)
User.create!(username: "bob", password: "test", email: "bob@test.com", admin: false)
User.create!(username: "heather", password: "test", email: "heather@test.com", admin: false)
User.create!(username: "allison", password: "test", email: "allison@test.com", admin: false)
User.create!(username: "spimonid", password: "test", email: "spimonid@test.com", admin: true)

Company.create!(name: "Outreach")
Company.create!(name: "Miro")
Company.create!(name: "Gong")
Company.create!(name: "Pluralsight")
Company.create!(name: "Github")
Company.create!(name: "Yahoo")

Job.create!(company_id: 1, role: "Front End Engineer", remote: true, technologies: "Javascript")
Job.create!(company_id: 2, role: "Back End Developer", remote: false, technologies: "Python")
Job.create!(company_id: 3, role: "Full Stack Developer", remote: true, technologies: "JavaScript, mySQL")
Job.create!(company_id: 4, role: "Data Engineer", remote: true, technologies: "Ruby, Javascript")
Job.create!(company_id: 2, role: "Full Stack Developer", remote: true, technologies: "PHP")

Person.create!(name: "Jon", company_id: 1, role: "Senior Software Engineer")
Person.create!(name: "Allie", company_id: 1, role: "Database Engineer")
Person.create!(name: "Sam", company_id: 2, role: "Engineering Manager")
Person.create!(name: "Reece", company_id: 2, role: "Technical Recruiter")
Person.create!(name: "Connor", company_id: 3, role: "Senior Front End Software Engineer")
Person.create!(name: "Callum", company_id: 6, role: "Software Engineer")
Person.create!(name: "Sarah", company_id: 6, role: "Sr. Engineering Manager")
Person.create!(name: "Jackie", company_id: 4, role: "Jr. Software Engineer")
Person.create!(name: "Alex", company_id: 5, role: "Data Engineer")
Person.create!(name: "Meg", company_id: 6, role: "Software Engineer")

SavedJob.create!(user_id: 1, job_id: 1)
SavedJob.create!(user_id: 4, job_id: 1)
SavedJob.create!(user_id: 3, job_id: 4)
SavedJob.create!(user_id: 5, job_id: 1)
SavedJob.create!(user_id: 5, job_id: 2)
SavedJob.create!(user_id: 5, job_id: 3)
SavedJob.create!(user_id: 5, job_id: 4)
SavedJob.create!(user_id: 5, job_id: 5)
SavedJob.create!(user_id: 7, job_id: 1)
SavedJob.create!(user_id: 8, job_id: 2)

SavedPerson.create(user_id: 4, person_id: 2, company_id: 1)
SavedPerson.create(user_id: 5, person_id: 2, company_id: 1)
SavedPerson.create(user_id: 5, person_id: 9, company_id: 5)
SavedPerson.create(user_id: 1, person_id: 8, company_id: 4)
SavedPerson.create(user_id: 2, person_id: 8, company_id: 4)
SavedPerson.create(user_id: 3, person_id: 2, company_id: 1)
SavedPerson.create(user_id: 3, person_id: 3, company_id: 2)
SavedPerson.create(user_id: 3, person_id: 4, company_id: 2)
SavedPerson.create(user_id: 3, person_id: 5, company_id: 3)
SavedPerson.create(user_id: 3, person_id: 6, company_id: 6)
